### ISSUE TITLE
Card Comments / Likes Icons

### ISSUE THREAD

**Issue by robmarshall** [BenjaminClark/indie-studio#5]
Heart and comment icons do not display on touch devices as there is no hover. 

Due to the likelihood of the theme being used more on mobiles, do we consider the likes/comments count important. My thoughts:

1. On mobile, show always, then keep current functionality on larger devices. This will not account for browsing on a large touch screen device.

or

2. Always show the comments/likes, no matter what device.

@BenjaminClark Thoughts?

**Comment by BenjaminClark** [comment]
I'm thinking it's cleaner not to have those icons on touch devices, so nice to leave it like it is. But if there is an easy way to remove the split second hover display when tapping a link, that would be good as seems a bit messy.

**Comment by robmarshall** [comment]
Added touch detection.

If touch, add class to body. The modules then don't have any hover
