### ISSUE TITLE
Gallery Post Light-box

### ISSUE THREAD

**Issue by robmarshall** [BenjaminClark/indie-studio#6]
Fancybox is not initiating in a gallery post. On click the user gets taken to an attachment page.

This seems to be caused by an incorrect link (the page, as opposed to the image URL) being passed to the attachment gallery. If this is removed will this effect IndiePresses ability to pass images to third parties?

This may also have SEO implications? Is it possible to allow a fallback to page link if no JS, but load the Fancybox image if there is? That way the SEO issue is also solved.

**Comment by ghost** [comment]
Updated Fancybox, this seems to work now
